name: CI - Backend Build Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'FitAppApi/**'

jobs:
  build_check:
    name: Build and Validate BE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore FitAppApi/FitAppApi.csproj

      - name: Build and Publish
        run: dotnet publish FitAppApi/FitAppApi.csproj -c Release -o ./publish --no-restore